name: htmx_app
description: A sample HTMX app
version: 1.0.0
publish: none

environment:
  sdk: ^3.3.0

dependencies:
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  shelf: ^1.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
